 # This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Dev05 Org Refresh

on:
  workflow_dispatch:

env:
  SF_USERNAME: ${{ vars.DEV05_USERNAME }}
  SF_PASSWORD: ${{ secrets.DEV05_PASSWORD }}
  WORKSPACE: ${{ github.workspace }}
  JOB_NAME: ${{ github.job }}
  BUILD_NUMBER : ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref }}
  RUN_BY: ${{ github.actor }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  Dev05_Org_Refresh:
    name: Dev05 Org Refresh
    runs-on: ubuntu-latest
    outputs:
      deploy_status: ${{ steps.update_job_status_var.outputs.deploy_status }}
    steps:
      - name: Valdiate Branch
        if: env.BRANCH_NAME != 'refs/heads/main'
        run: |
          echo "Branch Name is ${{ env.BRANCH_NAME }}. Please select main branch to deploy this."
          exit 1
      - name: Checkout Code from Github
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Ant
        id: sfdc_deploy_step
        run: ant -buildfile build/qa-pkg/dev05-sfdc-build.xml deployOnly
      - name: Update job status variable
        id: update_job_status_var
        if: ${{ success() || failure() }}
        run:
            echo "deploy_status=${{ job.status }}" >> "$GITHUB_OUTPUT"
      - name: Upload log job 1
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: log_deploy
          path: logfile.txt
  Post_Slack_Message:
      if: ${{ success() || failure() }}
      needs: Dev05_Org_Refresh
      name: Post to a Slack channel
      runs-on: ubuntu-latest
      steps:
        - name: Download log job 1
          uses: actions/download-artifact@v4
          with:
            name: log_deploy
        - name: Read log file
          id: read_file
          uses: andstor/file-reader-action@v1
          with:
            path: "logfile.txt"
        - name: File contents
          run: echo "${{ steps.read_file.outputs.contents }}"
              
        - name: Slack
          uses: slackapi/slack-github-action@v1.27.0
          with:
            channel-id: 'C07KLJKAF6G'
            slack-message: "GitHub Build Result: ${{needs.Dev05_Org_Refresh.outputs.deploy_status}}\nFailure Reason: ..."
            
